import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <video
          className="fixed inset-0 w-full h-full object-cover -z-10 opacity-75 pointer-events-none"
          autoPlay
          loop
          muted
          playsInline
          src="/video/HKk6d7CxCUOCEyRztfV2912558.mp4"
        />
        {children}
        <footer className="fixed bottom-6 left-0 right-0 w-full text-center p-0 text-black font-bold text-[20px]">
          create something magical on{" "}
          <a
            href="https://daisy.so"
            target="_blank"
            rel="noopener noreferrer"
            className="underline text-black font-bold"
          >
            daisy.so
          </a>
        </footer>
      </body>
    </html>
  );
}
